### ISSUE TITLE
mutate convert to int converts no data to 0

### ISSUE THREAD

**Issue by Faheemul** [logstash-plugins/logstash-filter-mutate#68]
when we are converting some values to integer, if value is null then we see its value as 0, which gives wrong information in case where for some values we get values as 0.

EX:
if message is SignalStrength=
then we see #SignalStrength 0 as KV pair
we expect blank vlaue.

since in some message we get SignalStrength=0
then we cannot differentiate between if the value is real 0 or it is created by logtsatsh as 0 when there is no data in value.

**Comment by jakelandis** [comment]
I took a quick stab at addressing this on PR #108 , however, as @yaauie pointed out by _NOT_ doing a conversion we could possibly increase the chances of Elasticsearch mapping errors by emmiting divergent types for the same field. 

I think for this case using a [conditional](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals) and [tags](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-add_tag) would be the best solution here. 

@Faheemul - I am going to close this issue, since I don't see a path forward here without increasing the chances for mapping errors in Elasticsearch. Please re-open if you feel there is something I am missing.
